export { home, outside, human };

const home = [
  {
    id: 0,
    text: "Кто ест сено безо рта, тремя зубами?",
    help: "сельскохозяйственный инструмент",
    answer: "вилы",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 1,
    text: "Захочу, так поклонюсь, поленюсь, так повалюсь.",
    help: "инструмент",
    answer: "топор",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 2,
    text: "На дворе кланяется, <br>А домой придет — растянется.",
    help: "инструмент",
    answer: "топор",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 3,
    text: "Мужик идет из лесу, <br>Зеркало за поясом.",
    help: "инструмент",
    answer: "топор",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 4,
    text: "Мужик пошел в лес: <br>В лес идет — Домой глядит, <br>Из лесу идет — В лес глядит",
    help: "инструмент",
    answer: "топор",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 5,
    text: "И у нас,И у вас<br>Поросенок увяз.",
    help: "инструмент",
    answer: "клин",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 6,
    text: "Бежит боровок,<br>Разбитый лобок.",
    help: "инструмент",
    answer: "долото",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 7,
    text: "Скоро ест,<br>Мелко жует,<br>Сама не глотает,<br>Другой сыт бывает.",
    help: "инструмент",
    answer: "пила",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 8,
    text: "Туп конец,<br>Востён резец:<br>Режет листки,<br>Летят куски.",
    help: "красивый камушек",
    answer: "алмаз",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 9,
    text: "На полу, на лавке<br>Натыканы булавки",
    help: "деревянное",
    answer: "сучок",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 10,
    text: "Не ест,<br>Не лает,<br>В дом не пускает",
    help: "ты серьезно?",
    answer: "замок",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 11,
    text: "Сквозь потолок<br>Кишку проволок.",
    help: "огонь и тепло",
    answer: "труба",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 12,
    text: "Чего из избы не вытащишь.",
    help: "огонь и тепло",
    answer: "печь",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 13,
    text: "Летом спит,<br>Зимой ест;<br>Тело тепло,<br>А крови нет.",
    help: "огонь и тепло",
    answer: "печь",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 14,
    text: "Не выметешь,<br>Не выскребешь,<br>А время приде —<br>Сам выйде.",
    help: "огонь и тепло",
    answer: "дым",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 15,
    text: "У нас в печурочке<br>Золотые чурочки",
    help: "огонь и тепло",
    answer: "дрова",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 16,
    text: "Четыре брата<br>Под одной шапкой живут",
    help: "предметы дома",
    answer: "стол",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 17,
    text: "С ногами,<br>Без рук;<br>С боками,<br>Без ребер;<br>С сиденьем,<br>Без живота,<br>Со спиной,<br>Без головы.",
    help: "предметы дома",
    answer: "стул",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 18,
    text: "Четыре ноги,<br>Да не зверь;<br>Есть перья,<br>Да не птица.",
    help: "предметы дома",
    answer: "кровать",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 19,
    text: "Без рук,<br>Без ног,<br>Рубашки просит.",
    help: "предметы дома",
    answer: "подушка",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 20,
    text: "Висится, болтается,<br>Всяк за него хватается.",
    help: "предметы дома",
    answer: "полотенце",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 21,
    text: "Светленько,<br>Чистенько,<br>Посмотреть любенько.",
    help: "предметы дома",
    answer: "зеркало",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 22,
    text: "Что всегда ходит?<br>А с места не соходит?",
    help: "предметы дома",
    answer: "часы",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 23,
    text: "Черный конь<br>Прыгат в огонь.",
    help: "предметы дома",
    answer: "кочерга",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 24,
    text: "Дыр много,<br>А вылезть некуда.",
    help: "кухонная утварь",
    answer: "дуршлаг",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 25,
    text: "Несут свинью к овину,<br>На обоих концах по рылу.",
    help: "кухонная утварь",
    answer: "корыто",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 26,
    text: "Висит баба на грядках,<br>Вся в заплатках;<br>Заплата на заплате,<br>А дырье не зашито.",
    help: "кухонная утварь",
    answer: "корзина",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 27,
    text: "Гибкий лес<br>На бабу влез,<br>На этой вспотел,<br>На другую захотел.",
    help: "кухонная утварь",
    answer: "коромысло",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 28,
    text: "Выну изо рта ягодку,<br>Оближу и опять положу.",
    help: "кухонная утварь",
    answer: "ложка",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 29,
    text: "Без рук,Без ног<br>Лапшу крошит.",
    help: "кухонная утварь",
    answer: "нож",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 30,
    text: "Ел, ел конь<br>Да и в ясли упал.",
    help: "кухонная утварь",
    answer: "нож",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 31,
    text: "Никогда не ест.<br>А только пьет;<br>А как зашумит —<br>Всех приманит.",
    help: "кухонная утварь",
    answer: "самовар",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 32,
    text: "В небо дыра,<br>В землю дыра,<br>В середке огонь,<br>Кругом вода.",
    help: "кухонная утварь",
    answer: "самовар",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 33,
    text: "В брюхе — баня,<br>В носу — решето;<br>На голове — пупок,<br>Всего одна рука,<br>И та — на спине.",
    help: "кухонная утварь",
    answer: "чайник",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 34,
    text: "Меня одну не едят,<br>А без меня мало едят.",
    help: "еда и напитки",
    answer: "соль",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 35,
    text: "От воды родится,<br>Воды боится.",
    help: "еда и напитки",
    answer: "соль",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 36,
    text: "От воды родится<br>И в воду годится,<br>Мать свою увидитИ умрет.",
    help: "еда и напитки",
    answer: "соль",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 37,
    text: "Черна, мала крошка;<br>Соберут немножко,<br>В воде поварят —<br>Ребята съедят.",
    help: "еда и напитки",
    answer: "каша",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 38,
    text: "Сидит на ложке,<br>Свесив ножки.",
    help: "еда и напитки",
    answer: "лапша",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 39,
    text: "Что на сковороду наливают<br>Да вчетверо сгибают?",
    help: "еда и напитки",
    answer: "блин",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 40,
    text: "На железном мосту<br>Коковяки растут.",
    help: "еда и напитки",
    answer: "оладьи",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 41,
    text: "Чиста, да не вода,<br>Клейка, да не смола,<br>Бела, да не снег,<br>Сладка, да не мед;<br>От рогатого берут<br>И живулькам дают.",
    help: "еда и напитки",
    answer: "молоко",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 42,
    text: "Полна бочка вина;<br>Ни клепок, ни дна.",
    help: "еда и напитки",
    answer: "яйцо",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 43,
    text: "В одной бочке<br>Двойное пиво,<br>Да и не сболтается никогда.",
    help: "еда и напитки",
    answer: "яйцо",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 44,
    text: "Под ледком, ледком<br>Стоит чашечка с медком.",
    help: "еда и напитки",
    answer: "яйцо",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 45,
    text: "Нашел я шар, разбил его,<br>Увидел серебро и золото.",
    help: "еда и напитки",
    answer: "яйцо",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 46,
    text: "Черненько.Горяченько,<br>А все любят.",
    help: "еда и напитки",
    answer: "чай",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 47,
    text: "Весь свет обшила,<br>Сама нагая ходила.",
    help: "рукоделие",
    answer: "игла",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 48,
    text: "Железный жучок,<br>На кончике червячок.",
    help: "рукоделие",
    answer: "булавка",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 49,
    text: "Шла свинья из Питера,<br>Вся истыкана.",
    help: "рукоделие",
    answer: "наперсток",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 50,
    text: "На одной яме —<br>Сто ям с ямой.",
    help: "рукоделие",
    answer: "наперсток",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 51,
    text: "Маленько,<br>Кругленько,<br>А за хвост не поднять.",
    help: "рукоделие",
    answer: "клубок",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 52,
    text: "Суну — встанет,<br>Вытащу — повянет.",
    help: "часть одежды",
    answer: "рукав",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 53,
    text: "Маленький Данилка<br>В петелку удавился.",
    help: "часть одежды",
    answer: "пуговица",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 54,
    text: "Днем, как обруч,<br>Ночью, как уж;<br>Кто отгадает —<br>Будет мой муж.",
    help: "одежда",
    answer: "пояс",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 55,
    text: "По дороге я шел,<br>Две дороги нашел,<br>По обеим пошел.",
    help: "одежда",
    answer: "штаны",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 56,
    text: "Повыше коленца,<br>Пониже пупенца,<br>Во что суют,<br>Как зовут?",
    help: "часть одежды",
    answer: "карман",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 57,
    text: "Шумит, хохочет,<br>На девку хочет.",
    help: "одежда",
    answer: "сарафан",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 58,
    text: "Под лесом, лесом<br>Пестрые колеса висят,<br>Девок красят,<br>Молодцов дразнят.",
    help: "украшение",
    answer: "серьга",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 59,
    text: "На ветру шатается<br>И без ветру шатается,<br>А на мясе держится.",
    help: "украшение",
    answer: "серьга",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 60,
    text: "Около кола<br>Золотая трава.",
    help: "украшение",
    answer: "кольцо",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 61,
    text: "Стоит девка на горе,<br>Да дивуется дыре:<br>— Свет моя дыра,<br>Дыра золотая,<br>Куда тебя дети?<br>— На живое мясо вздети.",
    help: "украшение",
    answer: "кольцо",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 62,
    text: "Пять чуланов,<br>Одна дверь.",
    help: "одежда",
    answer: "перчатки",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 63,
    text: "Без мяса, без костей,<br>А все-таки пять пальцев.",
    help: "одежда",
    answer: "перчатка",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 64,
    text: "С виду — клин.<br>Развернешь — блин.",
    help: "в СПб всегда с собой",
    answer: "зонт",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 65,
    text: "Из тюрьмы в тюрьму скачет,<br>Весь мир обскачет,<br>Ни к чему сама не годна,<br>А всем нужна.",
    help: "тюрьма = кошелек",
    answer: "деньги",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 66,
    text: "Сидит баба на грядках,<br>Вся в заплатках;<br>Кто ни взглянет —<br>Тот заплачет.",
    help: "еда и напитки",
    answer: "лук",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 67,
    text: "Что без боли и печали приводит в слезы?",
    help: "еда и напитки",
    answer: "лук",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 68,
    text: "Сидит баба на грядках,<br>Вся в заплатках.",
    help: "еда и напитки",
    answer: "капуста",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 69,
    text: "Ни окошек,<br>Ни дверей,<br>Полна церковья людей.",
    help: "еда и напитки",
    answer: "огурец",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 70,
    text: "Между двух гор<br>Лежит Егор.",
    help: "это огурец, почему он Егор, это надо спросить у жителей Псковской губернии",
    answer: "огурец",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 71,
    text: "Дед — в земле,<br>Борода — на земле.",
    help: "еда и напитки",
    answer: "хрен",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 72,
    text: "Сидит девица<br>В темной темнице,<br>Коса — на улице.",
    help: "еда и напитки",
    answer: "морковь",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 73,
    text: "Алый сапог<br>В земле горит.",
    help: "еда и напитки",
    answer: "свекла",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 74,
    text: "Вверху зелено,<br>Внизу красно,<br>В землю вросло.",
    help: "еда и напитки",
    answer: "свекла",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 75,
    text: "Между гор,<br>Между ям<br>Сидит птица<br>Холуян,<br>Несет яйца —<br>Божий дар.",
    help: "еда и напитки",
    answer: "картофель",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 76,
    text: "Сам алый,<br>Сахарный;<br>Кафтан зеленый,<br>Бархатный.",
    help: "еда и напитки",
    answer: "арбуз",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 77,
    text: "Сижу на тереме,<br>Мала, как мышь,<br>Красна, как кровь,<br>Вкусна, как мед.",
    help: "еда и напитки",
    answer: "вишня",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 78,
    text: "Красненька Матрешка,<br>Беленько сердечко.",
    help: "еда и напитки",
    answer: "малина",
    done: false,
    fail: false,
    display: false,
  },
];

const outside = [
  {
    id: 0,
    text: "Дед против солнца стоит.",
    help: "в поле",
    answer: "подсолнечник",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 1,
    text: "Без рук,Без ног,<br>Стоит, как хлоп,<br>Ничего не говорит,<br>А птиц страшит.",
    help: "в поле",
    answer: "пугало",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 2,
    text: "За дворами,<br>За клетями<br>Парня девка ерепенит.",
    help: "трава",
    answer: "крапива",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 3,
    text: "Што та за трава, што слепые знають?",
    help: "кусь",
    answer: "крапива",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 4,
    text: "Хоть не огонь, а жжется.",
    help: "трава",
    answer: "крапива",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 5,
    text: "Стоит древо —<br>Пан-древо;<br>На этом древе<br>Листья шемаханские,<br>Трости бухарские,<br>Когти супостатские.",
    help: "куст",
    answer: "репейник",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 6,
    text: "Дедушка осердился,<br>В бабушку вцепился.",
    help: "куст",
    answer: "репейник",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 7,
    text: "Четыре четырки,<br>Две растопырки,<br>Один вилюн,<br>Один фыркун<br>И два стеклышка в нем.",
    help: "домашнее животное",
    answer: "лошадь",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 8,
    text: "Четыре ходастых,<br>Два бодастых,<br> Один стремохал<br>Да два тухтериха.",
    help: "домашнее животное",
    answer: "корова",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 9,
    text: "Идет Христос в избу,<br>Несет Христос в избу:<br>Два витня,<br>Два благовитня,<br>Два ухотка,<br>Промеж ног<br>Кузовок,<br>Позади метла тащится.",
    help: "домашнее животное",
    answer: "корова",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 10,
    text: "Был мал —<br>В четыре дудки играл;<br>Вырос велик —<br>Землю поднял.",
    help: "домашнее животное",
    answer: "бык",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 11,
    text: "Некто по полям хождаше,<br>Главу свою ниже плеч ношаше,<br>И прииде некто, его заклаше,<br>Власы на огне сожже,<br>А тело на древе повеси.",
    help: "домашнее животное",
    answer: "свинья",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 12,
    text: "Ничего не болит,<br>А все стонет.",
    help: "домашнее животное",
    answer: "свинья",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 13,
    text: "По горам, по горам<br>Ходит шуба да кафтан.",
    help: "домашнее животное",
    answer: "овца",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 14,
    text: "С бородой родился,<br>Богу угодился,<br>Святой быть не может.",
    help: "домашнее животное",
    answer: "козел",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 15,
    text: "Четыре четырки,<br>Две растопырки,<br>Седьмой вертун,<br>А сам ворчун.",
    help: "домашнее животное",
    answer: "собака",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 16,
    text: "Собой не птица,<br>Петь не поет,<br>Кто к хозяину идет -<br>Она знать дает.",
    help: "домашнее животное",
    answer: "собака",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 17,
    text: "Четыре четырки,<br>Две растопырки,<br>Один вертун,<br>Да два яхонта.",
    help: "домашнее животное",
    answer: "кошка",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 18,
    text: "Вся мохнатенька,<br>Четыре лапки,<br>Сама усатенька.",
    help: "домашнее животное",
    answer: "кошка",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 19,
    text: "Под полом, полом<br>Ходит барыня с колом,<br>Ищет барыню с хвостом.",
    help: "домашнее животное",
    answer: "кошка",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 20,
    text: "Бежит Наташка<br>В семидесяти рубашках;<br>Ветер дунет — и тело голо.",
    help: "домашнее животное",
    answer: "курица",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 21,
    text: "Из семидесяти листов<br>Подается ясный голосок<br>В темный лесок<br>И в высокий теремок.",
    help: "домашнее животное",
    answer: "петух",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 22,
    text: "Ходит царь круг города,<br>Носит честь на голове.",
    help: "домашнее животное",
    answer: "петух",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 23,
    text: "Эко ты дерево!<br>И зиму и лето зелено.",
    help: "не ель))",
    answer: "сосна",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 24,
    text: "Красненько,кругленько;<br>Красненько,кругленько,<br>Листочки продолговатеньки.",
    help: "дерево",
    answer: "рябина",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 25,
    text: "Течет, течет —<br>Не вытечет;<br>Бежит, бежит —<br>Не выбежит.",
    help: "природный водный поток",
    answer: "река",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 26,
    text: "Не море, не земля:<br>Корабли не плавают<br>И ходить нельзя.",
    help: "участок ландшафта",
    answer: "болото",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 27,
    text: "Стоит мужик над водою,<br>Трясет своей бородою.",
    help: "трава",
    answer: "камыш",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 28,
    text: "Из куста шипуля,<br>За ногу типуля.",
    help: "пресмыкающиеся",
    answer: "змея",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 29,
    text: "Выпуча глаза, сидит,<br>По-французски говорит,<br>По-блошьи прыгает,<br>По-человечьи плавает.",
    help: "земноводное",
    answer: "лягушка",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 30,
    text: "Синенька шубенка<br>Покрыла весь мир.",
    help: "вверх посмотри",
    answer: "небо",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 31,
    text: "Сито, Вито,<br>Кругловито,<br>Кто ни взглянет,<br>Тот заплачет.",
    help: "звезда",
    answer: "солнце",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 32,
    text: "Камень — Пламень.",
    help: "небесный объект",
    answer: "луна",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 33,
    text: "Чего на свете не перечтешь, что видно только ночью?",
    help: "небесные объекты",
    answer: "звезды",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 34,
    text: "Шумит, гудит<br>Целый век,<br>А не человек.",
    help: "природное явление",
    answer: "ветер",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 35,
    text: "Крупно, дробно зачастило,<br>Всю землю напоило.",
    help: "природное явление",
    answer: "дождь",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 36,
    text: "На небе стукнет,<br>На земле слышно.",
    help: "природное явление",
    answer: "гром",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 37,
    text: "Летит огневая стрела,<br>Никто ее не поймает:<br>Ни царь, ни царица,<br>Ни красная девица.",
    help: "природное явление",
    answer: "молния",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 38,
    text: "Прилетела пава,<br>Села на лаву,<br>Распустила перья<br>Для всякого зелья.",
    help: "время года",
    answer: "весна",
    done: false,
    fail: false,
    display: false,
  },
];

const human = [
  {
    id: 0,
    text: "Стоит волчище,<br>Разинул ртище.",
    help: "сооружение",
    answer: "колодец",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 1,
    text: "Собираются детки<br>В золотую клетку.",
    help: "сооружение",
    answer: "церковь",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 2,
    text: "Что с ушами и языком, а ничего неслышит и не понимает?",
    help: "часть сооружения",
    answer: "колокол",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 3,
    text: "За уши повесили,<br>За язык подергали.",
    help: "часть сооружения",
    answer: "колокол",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 4,
    text: "Кричит без языка,<br>Поет без горла,<br>Радует и бедует,<br>А сердце не чует.",
    help: "часть сооружения",
    answer: "колокол",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 5,
    text: "Живой мертвого бьет,<br>Мертвый голос издает,<br>На крик его народ идет.",
    help: "часть сооружения",
    answer: "колокол",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 6,
    text: "Войду в ельник,<br>Трясу березняк;<br>И жарко,<br>И ярко,<br>И хочется!",
    help: "сооружение",
    answer: "баня",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 7,
    text: "Висит килка<br>На четырех жилках.",
    help: "детская площадка",
    answer: "качели",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 8,
    text: "Какие люди всегда свободны от гостей?",
    help: "материальное положение",
    answer: "нищие",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 9,
    text: "Шелков клуб,<br>Семь дыр вокруг.",
    help: "часть тела",
    answer: "голова",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 10,
    text: "Что за обедом всего нужнее?",
    help: "часть тела",
    answer: "рот",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 11,
    text: "На море дощечка не гниет, неплесниет, а завсегда мокра.",
    help: "часть тела",
    answer: "язык",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 12,
    text: "Рядом два колодца, а между ими одна перегородка.",
    help: "часть тела",
    answer: "нос",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 13,
    text: "Кругло, горбато,<br>Около лохмато,<br>Придет беда —<br>Потечет вода.",
    help: "часть тела",
    answer: "глаз",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 14,
    text: "Под дугам, дугам<br>Висит яблоко с кругам.",
    help: "часть тела",
    answer: "глаз",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 15,
    text: "Плосконька досочка,<br>По краям — обшивочка,<br>А в середке — дырочка.",
    help: "часть тела",
    answer: "ухо",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 16,
    text: "У двух матерей<br>По пяти сыновей,<br>Одно имя всем.",
    help: "часть тела",
    answer: "палец",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 17,
    text: "Пришел милый<br>Да и повалил силой.",
    help: "вид отдыха",
    answer: "сон",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 18,
    text: "Без языка, а сказывается?",
    help: "чувство",
    answer: "боль",
    done: false,
    fail: false,
    display: false,
  },
  {
    id: 19,
    text: "Идут лесом,<br>Поют куролесом,<br>Несут деревянный пирог<br>С мясом.",
    help: "событие",
    answer: "похороны",
    done: false,
    fail: false,
    display: false,
  },
];
